### ISSUE TITLE
tuya_not_configured popup error, native tuya is fully working

### ISSUE THREAD

**Issue by dhennyspestana** [azerty9971/xtend_tuya#18] opened 2024-06-11 21:26 UTC
I tried xtend_tuya for the first time a couple weeks ago. I installed through HACS and I was able to make it work, but only for less than a day.
All my Tuya devices are still working fine, through Tuya App and HomeAssistant native integration.
I tried to remove and add xtend_tuya back, even deleted the files at the /config/custom_components/ directory and downloaded all again but all I can get is a "tuya_not_configured" popup right at the integration page. I also removed Tuya integration and went through the whole process (qr code and all), native Tuya is back working perfectly but xtend_tuya still returns the same popup error no matter what I try.
During the past few days, HomeAssistant has been restarted, rebooted, upgraded, new integrations were added and some other were removed. Since the message is not detailed enough, I'm out of ideas. Hope some one can shed some light here.
Thank you in advance.

![screenshot_xtend_tuya](https://github.com/azerty9971/xtend_tuya/assets/8443030/ba4b1e5a-e3aa-47fe-8aa4-c1597cad4b51)

**Comment by azerty9971** [comment] 2024-06-12 17:20
Hello,
Could you contact me at devun999999@gmail.com so that we can arrange a call (with video sharing)?

Because I've never seen this error before :).

Thanks in advance,
Azerty9971

**Comment by rogierfransen** [comment] 2024-06-13 11:21
Same issue here as well, please let me know if there is a fix available, or where I can find the logfiles, which I can share.

**Comment by azerty9971** [comment] 2024-06-13 17:38
I found a way to reproduce the issue, it should be fixed in a few minutes ;)

**Comment by azerty9971** [comment] 2024-06-13 18:02
This should now be fixed by release V1.1.1, please update and let me know...

Have a nice day,
Azerty

**Comment by rogierfransen** [comment] 2024-06-14 06:29
Working! Thank you very much.

**Comment by azerty9971** [comment] 2024-06-14 12:09
Glad I could help :)

**Closed by azerty9971** 2024-06-14 12:09 UTC

**Comment by dhennyspestana** [comment] 2024-06-20 16:47
Sorry for the late reply. It is indeed working after upgrading to v1.2.3! Thank you!! Keep up the good work here! :)
But now there is a (possibly) new issue (probably unrelated to the previous one that seems to be fixed). My main Tuya integration failed (for some reason I can't explain, HA web interface was stuck and not working and I forced a docker restart manually through ssh). When it was back online atfter a couple minutes, It forced me to reauthenticate both Tuya and xtendTuya but the QRcode that it shows is expired. I had to to delete both Tuya and xtendTuya then add them back. This behavior causes me a LOT of trouble because the convention names I use for entities are all messed up badly and I had to reconfigure all my dashboards.
Let me know if I can help somehow. The first message you replied here was redacted, I don't know how to reach you.
Thank you very much!
![screenshot_xtend_tuya_reconfigure_devices](https://github.com/azerty9971/xtend_tuya/assets/8443030/f6cc90d4-30d4-4440-a202-a50c5b90a07f)

**Comment by azerty9971** [comment] 2024-06-20 19:08
Hello,
I've sometimes had to reauthenticate with Tuya and/or xtended tuya and the QR code was working fine each time.

Could you try something? Next time it asks you to reauthenticate, if the QR code doesn't work then restart the HA instance and see if it fixes the issue...

If not, feel free to contact me on devun999999@gmail.com :).

Have a nice evening,
Azerty
