### ISSUE TITLE
Missing energy entity

### ISSUE THREAD

**Issue by gvizdpeter** [azerty9971/xtend_tuya#14] opened 2024-04-20 08:20 UTC
Hello, 

thank you very much for all your time invested in this project. I tried to follow installation guide from https://github.com/azerty9971/xtend_tuya?tab=readme-ov-file#installation with only difference being, that I have to use user code. Everything went well, intgreation is in my home assistant, but unfortunately I can not see Energy entity, that should represent current consumption, or any other entity from this integration, just devices. 

Integration version: commit ab65afce033b43d8c8e998b14236bc8e384406c7 from master
Home assistent version: 
  Core 2024.4.3
  Supervisor 2024.04.0
  Operating System 12.2
  Frontend 20240404.2

I am attaching screenshots from home assistent as well as diagnostics from Tuya and Xtended Tuya. Can you please help me somehow?

Thank you very much in advance for any response.
![Screenshot 2024-04-20 101315](https://github.com/azerty9971/xtend_tuya/assets/19418876/d119ed0d-2c6b-43db-8fd6-e9349045129a)
![Screenshot 2024-04-20 101532](https://github.com/azerty9971/xtend_tuya/assets/19418876/645a91c2-3d89-463a-a4a4-39276774377f)
[xtend_tuya-092470950447b90aed102cf46071f9ca-Bathroom-e2623a3b76f8125a7742abef68f2a88c.json](https://github.com/azerty9971/xtend_tuya/files/15047447/xtend_tuya-092470950447b90aed102cf46071f9ca-Bathroom-e2623a3b76f8125a7742abef68f2a88c.json)
[tuya-05ef2cac5f04768da659105629efd0c1-Bathroom-e2623a3b76f8125a7742abef68f2a88c.json](https://github.com/azerty9971/xtend_tuya/files/15047448/tuya-05ef2cac5f04768da659105629efd0c1-Bathroom-e2623a3b76f8125a7742abef68f2a88c.json)

**Comment by azerty9971** [comment] 2024-05-03 19:57
Hello,
Sorry for the delay.

I've checked and in fact the tuya cloud is not sending the delta energy consumptions (add_ele).

In the SmartLife/Tuya app do you see the consumption history?

Have a nice evening,
Azerty

**Comment by gvizdpeter** [comment] 2024-05-03 20:09
Hello, thank you for response. Yes in Tuya app I can see the consumption history.

Have a nice evening too.

**Comment by azerty9971** [comment] 2024-05-03 20:13
That's strange, can you contact me at devun999999@gmail.com so that we can have a look at it together?
Would you be available now?

**Comment by gvizdpeter** [comment] 2024-05-03 20:15
Really sorry, but I am not available now. I will send you mail later, so we can agree on some time, when we are both available.

**Comment by azerty9971** [comment] 2024-05-03 20:16
No worries ;)
Talk to you later ;)

**Comment by azerty9971** [comment] 2024-06-14 01:19
Bump, we'll have to look through your Tuya IOT cloud debugging platform to see the logs and try to figure out why you don't have these values being sent...

Can you contact me so that we make a screen sharing call please?

Thanks :)
Azerty

**Comment by gvizdpeter** [comment] 2024-06-18 20:36
Hello,

I am really sorry, but I am currently overwhelmed by work duties. I will
try to contact you as soon as things get better.
Really sorry for that, and really appreciate your initiative in this.

Thank you

pá 14. 6. 2024 v 3:19 odesílatel azerty9971 ***@***.***>
napsal:

**Comment by azerty9971** [comment] 2024-06-27 22:34
Hello,
The latest beta build of xtend_tuya might fix this issue...

Could you try to update to the 1.2.5b1 beta version and let me know?

Thanks!

**Comment by gvizdpeter** [comment] 2024-06-30 19:17
Hello, I tried today latest 1.2.5 version, but unfortunately result is still the same.

**Comment by azerty9971** [comment] 2024-06-30 19:36
Can you send me a new diagnostic file please?

That will tell me if anything has changed :)

Thanks !
Azerty

**Comment by gvizdpeter** [comment] 2024-06-30 19:41
Attached new diagnostics file. Thank you very much for looking into it.

[xtend_tuya-0c2264792871ed5e13226d96fcb19049-Bathroom-e2623a3b76f8125a7742abef68f2a88c.json](https://github.com/user-attachments/files/16045921/xtend_tuya-0c2264792871ed5e13226d96fcb19049-Bathroom-e2623a3b76f8125a7742abef68f2a88c.json)

**Comment by azerty9971** [comment] 2024-06-30 19:52
Hello,
Do you have the regular Tuya integration configured? (the one named "Tuya", not "Xtend Tuya".

Because it looks like you don't...

If you indeed don't, can you try 
1- deleting the configuration in Xtend Tuya
2- add the Tuya integration
3- readd the Xtend Tuya integration

Xtend Tuya is by design a plugin that fills in the gaps of the Tuya integration, it does not replace it (though it will work without the Tuya integration)

Let me know if that fixes your issues, because now the entities should be there when you add the Tuya integration ;)

**Comment by azerty9971** [comment] 2024-06-30 19:55
Also, watch out that by default, the Current, Voltage and Power entities are disabled, once you've configure the Tuya integration, head to your device page and look at the "Show hidden entities" for these values ;)

**Comment by azerty9971** [comment] 2024-06-30 19:59
Disregard my previous comment, I misremembered the original issue and indeed, it's not fixed yet, I'll try a different approach ;)

Keep you posted when it's ready ;)

**Comment by azerty9971** [comment] 2024-07-30 19:11
Hello,
The new approach has just been released in 2.0.0-beta.1 :)

Can you try this new version, and add the Tuya Cloud credentials like we used to do in the old days? (go to the XT Tuya integration page, click configure and enter the credentials in there):
example in this video on how to do it:
https://www.youtube.com/watch?v=y6kNHIYcJ5c

Thanks in advance and have fun!
Azerty

**Closed** 2024-08-06 14:03 UTC
